<program>    ::= <stmt_list>
<stmt_list>  ::= <stmt>
              | <stmt> \n <stmt_list>
<stmt>       ::= let <var> = <expression>
              | 

<var>        ::= <init_char><char>*

<init_char>  ::= is_alpha()
              | _

<char>       ::= is_alpha()
              | is_digit()
              | _

<expression> ::= <expression>.<expression> 
              | <literal>
              | <var>

<literal>    ::= <string>
              | <number>
              | <process>

<string>     ::= " <inner_string> "
<process>    ::= ` <inner_string> `
<number>     ::= 0-9*[.0-9*]
